// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Models;

#nullable disable

namespace WebAPP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241105171116_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("WebApp.Models.Services.ContactEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("birth_date");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("contacts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(1990, 1, 1),
                            Category = 0,
                            Created = new DateTime(2024, 11, 5, 18, 11, 15, 229, DateTimeKind.Local).AddTicks(1059),
                            Email = "",
                            FirstName = "Jan",
                            LastName = "Kowalski",
                            PhoneNumber = "123 456 789"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(1995, 5, 5),
                            Category = 0,
                            Created = new DateTime(2024, 11, 5, 18, 11, 15, 229, DateTimeKind.Local).AddTicks(1104),
                            Email = "",
                            FirstName = "Anna",
                            LastName = "Nowak",
                            PhoneNumber = "987 654 321"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(2000, 10, 10),
                            Category = 0,
                            Created = new DateTime(2024, 11, 5, 18, 11, 15, 229, DateTimeKind.Local).AddTicks(1167),
                            Email = "",
                            FirstName = "Piotr",
                            LastName = "Wiśniewski",
                            PhoneNumber = "456 789 123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
